import uuid
from django.db import models
from django.conf import settings


class VoiceWorkflow(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    # The actual graph structure sent from a Frontend React-Flow builder
    graph_schema = models.JSONField(default=dict, help_text="Contains 'nodes' and 'edges'")
    is_active = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.name} (User: {self.user.username})"


class KnowledgeBaseDocument(models.Model):
    """Model to track uploaded documents in the knowledge base."""
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True, blank=True)
    filename = models.CharField(max_length=255)
    file_type = models.CharField(max_length=50)  # pdf, txt, etc.
    file_size = models.IntegerField(help_text="File size in bytes")
    chunk_count = models.IntegerField(default=0, help_text="Number of chunks created from this document")
    uploaded_at = models.DateTimeField(auto_now_add=True)
    description = models.TextField(blank=True, help_text="Optional description of the document")
    
    class Meta:
        ordering = ['-uploaded_at']
        verbose_name = "Knowledge Base Document"
        verbose_name_plural = "Knowledge Base Documents"
    
    def __str__(self):
        return f"{self.filename} ({self.chunk_count} chunks)"


class Ticket(models.Model):
    """Support ticket created by the voice agent."""
    STATUS_CHOICES = [
        ('open', 'Open'),
        ('in_progress', 'In Progress'),
        ('resolved', 'Resolved'),
        ('closed', 'Closed'),
    ]
    PRIORITY_CHOICES = [
        ('low', 'Low'),
        ('medium', 'Medium'),
        ('high', 'High'),
        ('urgent', 'Urgent'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField(max_length=255)
    description = models.TextField()
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='open')
    priority = models.CharField(max_length=20, choices=PRIORITY_CHOICES, default='medium')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='tickets'
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Support Ticket"
        verbose_name_plural = "Support Tickets"

    def __str__(self):
        return f"[{self.status.upper()}] {self.title}"


class DraftEmail(models.Model):
    """Email draft generated by the voice agent."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    subject = models.CharField(max_length=255)
    body = models.TextField()
    recipient = models.CharField(max_length=255, blank=True, default='')
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL,
        null=True, blank=True, related_name='draft_emails'
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']
        verbose_name = "Draft Email"
        verbose_name_plural = "Draft Emails"

    def __str__(self):
        return f"Draft: {self.subject}"